### ISSUE TITLE
Tool is testing eod sequences which an attacker cannot produce

### ISSUE THREAD

**Issue by The-Login** [hannob/smtpsmug#8]
First of all, thanks for the tool!
I've just received an issue for my version of the tool: https://github.com/The-Login/SMTP-Smuggling-Tools/issues/6  
For now, we should remove `<CR><LF>.whatever` test cases for inbound scanning to reduce false positives.  
What do you think?

**Comment by wietse-postfix** [comment]
As the original reporter of these false positives, I agree.   An attacker cannot cause a mail service to send `<CRLF>.<non-CRLF>`, that will always be dot-stuffed as  `<CRLF>..<non-CRLF>` which cannot trigger smuggling.

**Comment by hannob** [comment]
I think there are different questions here. One is: What does specifically lead to an SMTP smuggling attack? The other is: How should mailservers behave correctly?

Given that the RFC is very clear that an \r character alone (i.e. not in an \r\n combination) is invalid, if a mailserver receives a sequence like "\r\n.\r", or any other form of isolated \r character, the correct behavior is to reject them (same for isolated \n characters) and answer with an error. So I think these tests are valid, and a well-behaving mailserver should reject these inputs.

It also appears to me that this is the safest way to handle not just SMTP smuggling, but any potential form of injection/newline confusion attacks.

**Comment by wietse-postfix** [comment]
Yes, it would be better if email servers did not do that.

However, my point is that there is no vulnerability. There exists no email service  that is willing to forward such a CRLF-dot-nonCRLF sequence. I will fix this in the coming week or so, but only to silence tools.

Have you considered tooling to find out if an email service is willing to forward non-standard End-of-DATA like sequences? Seems to me that at this point people are looking at one half  of the problem.

**Comment by The-Login** [comment]
As already mentioned here (https://github.com/The-Login/SMTP-Smuggling-Tools/issues/6), I would not 100% trust outbound servers with that assumption. There might still be some exotic/proprietary software allowing just that (see Exchange Online and GMX).  

Regarding the analysis of outbound SMTP servers, Hanno's tooling can already be used for that in combination with https://github.com/Email-Analysis-Toolkit/fake-mail-server. As announced, I'm already working on a more specific solution/server.

**Comment by wietse-postfix** [comment]
All production email services will prepend a '.' proprietary or not. If they didn't do that, then SMTP would be broken all the time.

But rest assured, I'll fix this to silence your tool, not because it fixes a problem.

**Comment by hannob** [comment]
I have updated the README with some hopefully better explanations. While I understand that not all such sequences will cause an SMTP smuggling vulnerability, they are still invalid sequences and should as such be rejected.
